name: Deploy

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION : "sa-east-1" #Change to reflect your Region

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production  # this maps to your production environment in repo settings
    steps:
      - uses: actions/checkout@v3
      - name: Read env vars
        run: |
          echo ${{ env.DEPLOY_ROLE }}
      - name: Read env vars2
        run: |
          echo ${{ env.SHORT }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Your production deploy commands here.
  
  deploy-development:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: development  # maps to your development environment
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Development
        run: |
          echo "Deploying to development..."
          # Your development deploy commands here.
